/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolucaoFinanceiraRouteImport } from './routes/solucao-financeira'
import { Route as MilhasRouteImport } from './routes/milhas'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LancamentosRouteImport } from './routes/lancamentos'
import { Route as ImportarRouteImport } from './routes/importar'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as CartoesRouteImport } from './routes/cartoes'
import { Route as BaseRouteImport } from './routes/base'
import { Route as AnotacoesRouteImport } from './routes/anotacoes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MilhasIndexRouteImport } from './routes/milhas.index'
import { Route as MilhasResgatesRouteImport } from './routes/milhas.resgates'
import { Route as MilhasRegistrosRouteImport } from './routes/milhas.registros'
import { Route as MilhasProgramasRouteImport } from './routes/milhas.programas'
import { Route as MilhasPlanejamentoRouteImport } from './routes/milhas.planejamento'
import { Route as MilhasGanhosRouteImport } from './routes/milhas.ganhos'
import { Route as MilhasConfigRouteImport } from './routes/milhas.config'
import { Route as MilhasComparacaoRouteImport } from './routes/milhas.comparacao'
import { Route as ApiPublicFixBalancesRouteImport } from './routes/api/public/fix-balances'

const SolucaoFinanceiraRoute = SolucaoFinanceiraRouteImport.update({
  id: '/solucao-financeira',
  path: '/solucao-financeira',
  getParentRoute: () => rootRouteImport,
} as any)
const MilhasRoute = MilhasRouteImport.update({
  id: '/milhas',
  path: '/milhas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LancamentosRoute = LancamentosRouteImport.update({
  id: '/lancamentos',
  path: '/lancamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportarRoute = ImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const CartoesRoute = CartoesRouteImport.update({
  id: '/cartoes',
  path: '/cartoes',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseRoute = BaseRouteImport.update({
  id: '/base',
  path: '/base',
  getParentRoute: () => rootRouteImport,
} as any)
const AnotacoesRoute = AnotacoesRouteImport.update({
  id: '/anotacoes',
  path: '/anotacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MilhasIndexRoute = MilhasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MilhasRoute,
} as any)
const MilhasResgatesRoute = MilhasResgatesRouteImport.update({
  id: '/resgates',
  path: '/resgates',
  getParentRoute: () => MilhasRoute,
} as any)
const MilhasRegistrosRoute = MilhasRegistrosRouteImport.update({
  id: '/registros',
  path: '/registros',
  getParentRoute: () => MilhasRoute,
} as any)
const MilhasProgramasRoute = MilhasProgramasRouteImport.update({
  id: '/programas',
  path: '/programas',
  getParentRoute: () => MilhasRoute,
} as any)
const MilhasPlanejamentoRoute = MilhasPlanejamentoRouteImport.update({
  id: '/planejamento',
  path: '/planejamento',
  getParentRoute: () => MilhasRoute,
} as any)
const MilhasGanhosRoute = MilhasGanhosRouteImport.update({
  id: '/ganhos',
  path: '/ganhos',
  getParentRoute: () => MilhasRoute,
} as any)
const MilhasConfigRoute = MilhasConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => MilhasRoute,
} as any)
const MilhasComparacaoRoute = MilhasComparacaoRouteImport.update({
  id: '/comparacao',
  path: '/comparacao',
  getParentRoute: () => MilhasRoute,
} as any)
const ApiPublicFixBalancesRoute = ApiPublicFixBalancesRouteImport.update({
  id: '/api/public/fix-balances',
  path: '/api/public/fix-balances',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anotacoes': typeof AnotacoesRoute
  '/base': typeof BaseRoute
  '/cartoes': typeof CartoesRoute
  '/conta': typeof ContaRoute
  '/financeiro': typeof FinanceiroRoute
  '/importar': typeof ImportarRoute
  '/lancamentos': typeof LancamentosRoute
  '/login': typeof LoginRoute
  '/milhas': typeof MilhasRouteWithChildren
  '/solucao-financeira': typeof SolucaoFinanceiraRoute
  '/milhas/comparacao': typeof MilhasComparacaoRoute
  '/milhas/config': typeof MilhasConfigRoute
  '/milhas/ganhos': typeof MilhasGanhosRoute
  '/milhas/planejamento': typeof MilhasPlanejamentoRoute
  '/milhas/programas': typeof MilhasProgramasRoute
  '/milhas/registros': typeof MilhasRegistrosRoute
  '/milhas/resgates': typeof MilhasResgatesRoute
  '/milhas/': typeof MilhasIndexRoute
  '/api/public/fix-balances': typeof ApiPublicFixBalancesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anotacoes': typeof AnotacoesRoute
  '/base': typeof BaseRoute
  '/cartoes': typeof CartoesRoute
  '/conta': typeof ContaRoute
  '/financeiro': typeof FinanceiroRoute
  '/importar': typeof ImportarRoute
  '/lancamentos': typeof LancamentosRoute
  '/login': typeof LoginRoute
  '/solucao-financeira': typeof SolucaoFinanceiraRoute
  '/milhas/comparacao': typeof MilhasComparacaoRoute
  '/milhas/config': typeof MilhasConfigRoute
  '/milhas/ganhos': typeof MilhasGanhosRoute
  '/milhas/planejamento': typeof MilhasPlanejamentoRoute
  '/milhas/programas': typeof MilhasProgramasRoute
  '/milhas/registros': typeof MilhasRegistrosRoute
  '/milhas/resgates': typeof MilhasResgatesRoute
  '/milhas': typeof MilhasIndexRoute
  '/api/public/fix-balances': typeof ApiPublicFixBalancesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anotacoes': typeof AnotacoesRoute
  '/base': typeof BaseRoute
  '/cartoes': typeof CartoesRoute
  '/conta': typeof ContaRoute
  '/financeiro': typeof FinanceiroRoute
  '/importar': typeof ImportarRoute
  '/lancamentos': typeof LancamentosRoute
  '/login': typeof LoginRoute
  '/milhas': typeof MilhasRouteWithChildren
  '/solucao-financeira': typeof SolucaoFinanceiraRoute
  '/milhas/comparacao': typeof MilhasComparacaoRoute
  '/milhas/config': typeof MilhasConfigRoute
  '/milhas/ganhos': typeof MilhasGanhosRoute
  '/milhas/planejamento': typeof MilhasPlanejamentoRoute
  '/milhas/programas': typeof MilhasProgramasRoute
  '/milhas/registros': typeof MilhasRegistrosRoute
  '/milhas/resgates': typeof MilhasResgatesRoute
  '/milhas/': typeof MilhasIndexRoute
  '/api/public/fix-balances': typeof ApiPublicFixBalancesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anotacoes'
    | '/base'
    | '/cartoes'
    | '/conta'
    | '/financeiro'
    | '/importar'
    | '/lancamentos'
    | '/login'
    | '/milhas'
    | '/solucao-financeira'
    | '/milhas/comparacao'
    | '/milhas/config'
    | '/milhas/ganhos'
    | '/milhas/planejamento'
    | '/milhas/programas'
    | '/milhas/registros'
    | '/milhas/resgates'
    | '/milhas/'
    | '/api/public/fix-balances'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anotacoes'
    | '/base'
    | '/cartoes'
    | '/conta'
    | '/financeiro'
    | '/importar'
    | '/lancamentos'
    | '/login'
    | '/solucao-financeira'
    | '/milhas/comparacao'
    | '/milhas/config'
    | '/milhas/ganhos'
    | '/milhas/planejamento'
    | '/milhas/programas'
    | '/milhas/registros'
    | '/milhas/resgates'
    | '/milhas'
    | '/api/public/fix-balances'
  id:
    | '__root__'
    | '/'
    | '/anotacoes'
    | '/base'
    | '/cartoes'
    | '/conta'
    | '/financeiro'
    | '/importar'
    | '/lancamentos'
    | '/login'
    | '/milhas'
    | '/solucao-financeira'
    | '/milhas/comparacao'
    | '/milhas/config'
    | '/milhas/ganhos'
    | '/milhas/planejamento'
    | '/milhas/programas'
    | '/milhas/registros'
    | '/milhas/resgates'
    | '/milhas/'
    | '/api/public/fix-balances'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnotacoesRoute: typeof AnotacoesRoute
  BaseRoute: typeof BaseRoute
  CartoesRoute: typeof CartoesRoute
  ContaRoute: typeof ContaRoute
  FinanceiroRoute: typeof FinanceiroRoute
  ImportarRoute: typeof ImportarRoute
  LancamentosRoute: typeof LancamentosRoute
  LoginRoute: typeof LoginRoute
  MilhasRoute: typeof MilhasRouteWithChildren
  SolucaoFinanceiraRoute: typeof SolucaoFinanceiraRoute
  ApiPublicFixBalancesRoute: typeof ApiPublicFixBalancesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solucao-financeira': {
      id: '/solucao-financeira'
      path: '/solucao-financeira'
      fullPath: '/solucao-financeira'
      preLoaderRoute: typeof SolucaoFinanceiraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/milhas': {
      id: '/milhas'
      path: '/milhas'
      fullPath: '/milhas'
      preLoaderRoute: typeof MilhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lancamentos': {
      id: '/lancamentos'
      path: '/lancamentos'
      fullPath: '/lancamentos'
      preLoaderRoute: typeof LancamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importar': {
      id: '/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof ImportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cartoes': {
      id: '/cartoes'
      path: '/cartoes'
      fullPath: '/cartoes'
      preLoaderRoute: typeof CartoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base': {
      id: '/base'
      path: '/base'
      fullPath: '/base'
      preLoaderRoute: typeof BaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anotacoes': {
      id: '/anotacoes'
      path: '/anotacoes'
      fullPath: '/anotacoes'
      preLoaderRoute: typeof AnotacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/milhas/': {
      id: '/milhas/'
      path: '/'
      fullPath: '/milhas/'
      preLoaderRoute: typeof MilhasIndexRouteImport
      parentRoute: typeof MilhasRoute
    }
    '/milhas/resgates': {
      id: '/milhas/resgates'
      path: '/resgates'
      fullPath: '/milhas/resgates'
      preLoaderRoute: typeof MilhasResgatesRouteImport
      parentRoute: typeof MilhasRoute
    }
    '/milhas/registros': {
      id: '/milhas/registros'
      path: '/registros'
      fullPath: '/milhas/registros'
      preLoaderRoute: typeof MilhasRegistrosRouteImport
      parentRoute: typeof MilhasRoute
    }
    '/milhas/programas': {
      id: '/milhas/programas'
      path: '/programas'
      fullPath: '/milhas/programas'
      preLoaderRoute: typeof MilhasProgramasRouteImport
      parentRoute: typeof MilhasRoute
    }
    '/milhas/planejamento': {
      id: '/milhas/planejamento'
      path: '/planejamento'
      fullPath: '/milhas/planejamento'
      preLoaderRoute: typeof MilhasPlanejamentoRouteImport
      parentRoute: typeof MilhasRoute
    }
    '/milhas/ganhos': {
      id: '/milhas/ganhos'
      path: '/ganhos'
      fullPath: '/milhas/ganhos'
      preLoaderRoute: typeof MilhasGanhosRouteImport
      parentRoute: typeof MilhasRoute
    }
    '/milhas/config': {
      id: '/milhas/config'
      path: '/config'
      fullPath: '/milhas/config'
      preLoaderRoute: typeof MilhasConfigRouteImport
      parentRoute: typeof MilhasRoute
    }
    '/milhas/comparacao': {
      id: '/milhas/comparacao'
      path: '/comparacao'
      fullPath: '/milhas/comparacao'
      preLoaderRoute: typeof MilhasComparacaoRouteImport
      parentRoute: typeof MilhasRoute
    }
    '/api/public/fix-balances': {
      id: '/api/public/fix-balances'
      path: '/api/public/fix-balances'
      fullPath: '/api/public/fix-balances'
      preLoaderRoute: typeof ApiPublicFixBalancesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MilhasRouteChildren {
  MilhasComparacaoRoute: typeof MilhasComparacaoRoute
  MilhasConfigRoute: typeof MilhasConfigRoute
  MilhasGanhosRoute: typeof MilhasGanhosRoute
  MilhasPlanejamentoRoute: typeof MilhasPlanejamentoRoute
  MilhasProgramasRoute: typeof MilhasProgramasRoute
  MilhasRegistrosRoute: typeof MilhasRegistrosRoute
  MilhasResgatesRoute: typeof MilhasResgatesRoute
  MilhasIndexRoute: typeof MilhasIndexRoute
}

const MilhasRouteChildren: MilhasRouteChildren = {
  MilhasComparacaoRoute: MilhasComparacaoRoute,
  MilhasConfigRoute: MilhasConfigRoute,
  MilhasGanhosRoute: MilhasGanhosRoute,
  MilhasPlanejamentoRoute: MilhasPlanejamentoRoute,
  MilhasProgramasRoute: MilhasProgramasRoute,
  MilhasRegistrosRoute: MilhasRegistrosRoute,
  MilhasResgatesRoute: MilhasResgatesRoute,
  MilhasIndexRoute: MilhasIndexRoute,
}

const MilhasRouteWithChildren =
  MilhasRoute._addFileChildren(MilhasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnotacoesRoute: AnotacoesRoute,
  BaseRoute: BaseRoute,
  CartoesRoute: CartoesRoute,
  ContaRoute: ContaRoute,
  FinanceiroRoute: FinanceiroRoute,
  ImportarRoute: ImportarRoute,
  LancamentosRoute: LancamentosRoute,
  LoginRoute: LoginRoute,
  MilhasRoute: MilhasRouteWithChildren,
  SolucaoFinanceiraRoute: SolucaoFinanceiraRoute,
  ApiPublicFixBalancesRoute: ApiPublicFixBalancesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
